name: Deploy Little Lemon API

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/var/www/little-lemon"  
        
    # - name: Execute commands via SSH
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.DROPLET_IP }}
    #     username: ${{ secrets.DROPLET_USER }}
    #     key: ${{ secrets.DROPLET_KEY }}
    #     script: |
    #       cd /path/to/your/project
    #       python -m venv venv
    #       source venv/bin/activate
    #       pip install -r requirements.txt
    #       python manage.py migrate
    #       python manage.py collectstatic --noinput
    #       systemctl restart gunicorn  # Assuming you're using systemd for Gunicorn
    #       systemctl restart nginx
