name: Deploy Little Lemon API

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Droplet
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./
          target: /var/www/api-lemon

      - name: Set up environment and install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/api-lemon || exit
            if [ ! -d "env" ]; then
                python3 -m venv env
            fi
            source env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run Django management commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/api-lemon
            source env/bin/activate
            python manage.py makemigrations --no-input
            python manage.py migrate --no-input
            python manage.py collectstatic --no-input

      - name: Restart Gunicorn and Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # sudo systemctl restart gunicorn
            sudo systemctl restart nginx

